-- Add new_design_svg_url column to project_measurements table
-- This stores the URL of SVG design files generated by external services

ALTER TABLE project_measurements
ADD COLUMN IF NOT EXISTS new_design_svg_url TEXT;

COMMENT ON COLUMN project_measurements.new_design_svg_url IS
'URL of the new design SVG file generated by external design service. Business plan feature.';
